services:
  - type: web
    runtime: node
    name: khata-app-api
    plan: free
    rootDir: .
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CLIENT_URL
        value: https://khata-app-web.onrender.com

  - type: web
    runtime: static
    name: khata-app-web
    rootDir: client
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://khata-app-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html